### ISSUE TITLE
Does not allow unicode characters in settings.json

### ISSUE THREAD

**Issue by andrewjong** [longouyang/cosub#11]
#When I try to use Chinese characters for the title and description fields of settings.json, cosub crashes with the following error:
```
Traceback (most recent call last):
  File "/home/andrew/.bin/anaconda2/envs/mturk/bin/cosub", line 11, in <module>
    load_entry_point('cosub==0.1', 'console_scripts', 'cosub')()
  File "/home/andrew/.bin/anaconda2/envs/mturk/lib/python2.7/site-packages/cosub/runner.py", line 531, in go
    create_hit(settings)
  File "/home/andrew/.bin/anaconda2/envs/mturk/lib/python2.7/site-packages/cosub/runner.py", line 221, in create_hit
    dict_str(settings_raw)
  File "/home/andrew/.bin/anaconda2/envs/mturk/lib/python2.7/site-packages/cosub/runner.py", line 88, in dict_str
    'value': "\n" + dict_str(value, level + 1) if is_dict else str(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-13: ordinal not in range(128)
```
Do you know if there's an easy fix for this?

**Comment by longouyang** [comment]
It looks like there's an error with displaying your HIT settings when you use Unicode. Try commenting out line 221 and see if that works.
