### ISSUE TITLE
Error when downloading data in production mode

### ISSUE THREAD

**Issue by nataliavelez** [longouyang/cosub#12]
Hello! I've been using cosub for years, but this error is new to me. I launched 30 assignments for a new HIT and tried downloading them (**cosub -p download**). cosub skipped over the 16 assignments that I already had, but it gave me the following error message when it tried downloading the new 17th assignment:

```
Production mode
Currently have 16 results
Mturk has 25 results
Downloading page 1 of results
[Skipped _____ for the first 16 HITS]
Traceback (most recent call last):
  File "/Users/nataliavelez/anaconda/bin/cosub", line 9, in <module>
    load_entry_point('cosub==0.1', 'console_scripts', 'cosub')()
  File "/Users/nataliavelez/anaconda/lib/python2.7/site-packages/cosub/runner.py", line 505, in go
    get_results(HOST, mode, hit["id"])
  File "/Users/nataliavelez/anaconda/lib/python2.7/site-packages/cosub/runner.py", line 423, in get_results
    answers_dict[field_name] = json.loads( field_value )
  File "/Users/nataliavelez/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/nataliavelez/anaconda/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 1 column 10 (char 4 - 9)
```

Any idea how to get around this error? I tried going directly to the link to manage this HIT (`https://requester.mturk.com/mturk/manageHIT?HITId=_______`), but for some reason that link just takes me to the "Manage Batches" page (`https://requester.mturk.com/manage`) rather than to the usual page with results, so I have no way of downloading my data right now.

Thanks for your help!

**Comment by longouyang** [comment]
Hi Natalia -- I'm not sure what's happening here, but if you modify your copy of cosub a little, that might help shed some light on the error. Can you have it print out `field_value` before the line `answers_dict[field_name] = json.loads( field_value  )` and let me know what the output is?

**Comment by nataliavelez** [comment]
Sure! The output is:

```
true|true
```

**Comment by longouyang** [comment]
Hmm, [around line 433](https://github.com/longouyang/cosub/blob/master/cosub/runner.py#L433),  could you print out `a` for one of the 16 assignments that works and also for the 17th one that doesn't work?

**Comment by nataliavelez** [comment]
Hmm... `a` wouldn't print for the HIT that doesn't work at around line 433 (because it doesn't get that far), so I put the print statement at the start of the for loop (around line 407). The output for the assignments that work and don't work look pretty similar.

Assignment that worked:
`<boto.mturk.connection.Assignment object at 0x1046b5050>`

Assignment that didn't work:
`<boto.mturk.connection.Assignment object at 0x1046b52d0>`

**Comment by longouyang** [comment]
Paper trail: Natalia and I chatted a little about this on Slack. She sent me her credentials and HIT info; I tried reproducing her issue but couldn't -- I was able to download all the files.

**Comment by longouyang** [comment]
Paper trail: I had mentioned to Natalia that I typically use cosub within virtualenv. She tried that and that fixed the issue -- she was able to download all the data.

Todo: figure out whether there a differences between a virtualenv and non-virtualenv install.
